// UIPage.h - Manages building pages and displaying menu top pages
//
// SPDX-License-Identifier: MIT

#pragma once
#include "UIPage.h"
#include <rvl/types.h>

namespace UI
{

namespace SceneKind
{
enum {
    Menu = 1,
    Race = 2,
    Test = 3,
    Globe = 4
};
} // namespace SceneKind

enum {
    SCENE_POWER_OFF_WII = 0x00,
    SCENE_RETURN_TO_WII_MENU_1 = 0x04,
    SCENE_RETURN_TO_WII_MENU_2 = 0x05,
    SCENE_TEST_6 = 0x06,
    SCENE_TEST_7 = 0x07,
    SCENE_TEST_8 = 0x08,
    SCENE_TEST_9 = 0x09,
    SCENE_TEST_A = 0x0A,
    SCENE_TEST_B = 0x0B,
    SCENE_TEST_C = 0x0C,
    SCENE_TEST_D = 0x0D,
    SCENE_TEST_E = 0x0E,
    SCENE_TEST_F = 0x0F,
    SCENE_CREATE_NEW_SAVE = 0x10,
    SCENE_CORRUPTED_SAVE = 0x11,
    SCENE_COUNTRY_CHANGED = 0x12,
    SCENE_GAME_CANNOT_BE_SAVED = 0x13,
    SCENE_CANNOT_ACCESS_SYSTEM_MEMORY = 0x14,
    SCENE_CANNOT_ACCESS_MII_DATA = 0x15,
    SCENE_ESRB_NOTICE = 0x16,
    SCENE_RECOMMEND_60HZ_1 = 0x17,
    SCENE_RECOMMEND_60HZ_2 = 0x18,
    SCENE_GRAND_PRIX_PANORAMA = 0x19,
    SCENE_VS_RACE_PANORAMA = 0x1A,
    SCENE_BALLOON_BATTLE_PANORAMA = 0x1B,
    SCENE_MISSION_BOSS_PANORAMA = 0x1C,
    SCENE_TOURNAMENT_BOSS_PANORAMA = 0x1D,
    SCENE_GRAND_PRIX_GAMEPLAY = 0x1E,
    SCENE_TIME_TRIAL_GAMEPLAY = 0x1F,
    SCENE_1P_VS_RACE_GAMEPLAY = 0x20,
    SCENE_2P_VS_RACE_GAMEPLAY = 0x21,
    SCENE_3P_VS_RACE_GAMEPLAY = 0x22,
    SCENE_4P_VS_RACE_GAMEPLAY = 0x23,
    SCENE_1P_TEAM_VS_RACE_GAMEPLAY = 0x24,
    SCENE_2P_TEAM_VS_RACE_GAMEPLAY = 0x25,
    SCENE_3P_TEAM_VS_RACE_GAMEPLAY = 0x26,
    SCENE_4P_TEAM_VS_RACE_GAMEPLAY = 0x27,
    SCENE_1P_BATTLE_GAMEPLAY = 0x28,
    SCENE_2P_BATTLE_GAMEPLAY = 0x29,
    SCENE_3P_BATTLE_GAMEPLAY = 0x2A,
    SCENE_4P_BATTLE_GAMEPLAY = 0x2B,
    SCENE_MISSION_MODE_GAMEPLAY = 0x2C,
    SCENE_TOURNAMENT_GAMEPLAY = 0x2D,
    SCENE_GRAND_PRIX_REPLAY = 0x2E,
    SCENE_TIME_TRIAL_REPLAY = 0x2F,
    SCENE_GHOST_RACE_GAMEPLAY_1 = 0x30,
    SCENE_GHOST_RACE_GAMEPLAY_2 = 0x31,
    SCENE_WATCH_GHOST_FROM_CHANNEL = 0x32,
    SCENE_WATCH_GHOST_FROM_DOWNLOADS = 0x33,
    SCENE_WATCH_GHOST_FROM_MENU = 0x34,
    SCENE_GRAND_PRIX_AWARD = 0x35,
    SCENE_VS_RACE_AWARD = 0x36,
    SCENE_AWARD_37 = 0x37,
    SCENE_AWARD_38 = 0x38,
    SCENE_ENDING_NORMAL_A = 0x39,
    SCENE_ENDING_TRUE_A = 0x3A,
    SCENE_ENDING_NORMAL_B = 0x3B,
    SCENE_ENDING_TRUE_B = 0x3C,
    SCENE_CONGRATULATIONS = 0x3D,
    SCENE_CONGRATULATIONS_COMPLETE = 0x3E,
    SCENE_MAIN_MENU_FROM_BOOT = 0x3F,
    SCENE_MAIN_MENU_FROM_RESET = 0x40,
    SCENE_MAIN_MENU_FROM_MENU = 0x41,
    SCENE_MAIN_MENU_FROM_NEW_LICENSE = 0x42,
    SCENE_MAIN_MENU_FROM_LICENSE_43 = 0x43,
    SCENE_DEMO = 0x44,
    SCENE_MII_SELECT_1 = 0x45,
    SCENE_MII_SELECT_2 = 0x46,
    SCENE_LICENSE_SETTINGS = 0x47,
    SCENE_SINGLE_PLAYER_FROM_MENU = 0x48,
    SCENE_SINGLE_PLAYER_TT_CHANGE_CHARA = 0x49,
    SCENE_SINGLE_PLAYER_TT_CHANGE_COURSE = 0x4A,
    SCENE_SINGLE_PLAYER_VS_NEXT_RACE = 0x4B,
    SCENE_SINGLE_PLAYER_BT_NEXT_BATTLE = 0x4C,
    SCENE_SINGLE_PLAYER_MR_CHOOSE_MISSION = 0x4D,
    SCENE_SINGLE_PLAYER_CHAN_RACE_GHOST = 0x4E,
    SCENE_SINGLE_PLAYER_LB_RACE_GHOST = 0x4F,
    SCENE_SINGLE_PLAYER_LIST_RACE_GHOST = 0x50,
    SCENE_SEND_GHOST_TO_FRIEND = 0x51,
    SCENE_RACE_GHOST_FROM_CHAN_BOOT = 0x52,
    SCENE_WATCH_REPLAY_FROM_CHAN_BOOT = 0x53,
    SCENE_LOCAL_MULTIPLAYER = 0x54,
    SCENE_1P_WIFI = 0x55,
    SCENE_1P_WIFI_GLOBE_DISCONNECT = 0x56,
    SCENE_1P_WIFI_FROM_FIND_FRIEND = 0x57,
    SCENE_1P_WIFI_VS_VOTING = 0x58,
    SCENE_1P_WIFI_BATTLE_VOTING = 0x59,
    SCENE_2P_WIFI_SELECT_MII = 0x5A,
    SCENE_2P_WIFI = 0x5B,
    SCENE_2P_WIFI_GLOBE_DISCONNECT = 0x5C,
    SCENE_UNKNOWN_5D = 0x5D,
    SCENE_2P_WIFI_VS_VOTING = 0x5E,
    SCENE_2P_WIFI_BATTLE_VOTING = 0x5F,
    SCENE_1P_WIFI_FRIEND_ROOM_VS_VOTING = 0x60,
    SCENE_1P_WIFI_FRIEND_ROOM_TEAM_VS_VOTING = 0x61,
    SCENE_1P_WIFI_FRIEND_ROOM_BALLOON_VOTING = 0x62,
    SCENE_1P_WIFI_FRIEND_ROOM_COIN_VOTING = 0x63,
    SCENE_2P_WIFI_FRIEND_ROOM_VS_VOTING = 0x64,
    SCENE_2P_WIFI_FRIEND_ROOM_TEAM_VS_VOTING = 0x65,
    SCENE_2P_WIFI_FRIEND_ROOM_BALLOON_VOTING = 0x66,
    SCENE_2P_WIFI_FRIEND_ROOM_COIN_VOTING = 0x67,
    SCENE_1P_WIFI_VS_GAMEPLAY = 0x68,
    SCENE_2P_WIFI_VS_GAMEPLAY = 0x69,
    SCENE_1P_WIFI_VS_LIVE_VIEW = 0x6A,
    SCENE_2P_WIFI_VS_LIVE_VIEW = 0x6B,
    SCENE_1P_WIFI_BT_GAMEPLAY = 0x6C,
    SCENE_2P_WIFI_BT_GAMEPLAY = 0x6D,
    SCENE_1P_WIFI_BT_LIVE_VIEW = 0x6E,
    SCENE_2P_WIFI_BT_LIVE_VIEW = 0x6F,
    SCENE_1P_WIFI_FRIEND_VS_GAMEPLAY = 0x70,
    SCENE_1P_WIFI_FRIEND_TEAM_VS_GAMEPLAY = 0x71,
    SCENE_1P_WIFI_FRIEND_BALLOON_BT_GAMEPLAY = 0x72,
    SCENE_1P_WIFI_FRIEND_COIN_BT_GAMEPLAY = 0x73,
    SCENE_2P_WIFI_FRIEND_VS_GAMEPLAY = 0x74,
    SCENE_2P_WIFI_FRIEND_TEAM_VS_GAMEPLAY = 0x75,
    SCENE_2P_WIFI_FRIEND_BALLOON_BT_GAMEPLAY = 0x76,
    SCENE_2P_WIFI_FRIEND_COIN_BT_GAMEPLAY = 0x77,
    SCENE_WIFI_DISCONNECT_ERROR = 0x78,
    SCENE_WIFI_DISCONNECT_GENERAL = 0x79,
    SCENE_CHANNEL_FROM_MENU = 0x7A,
    SCENE_CHANNEL_FROM_CHECK_RANKINGS = 0x7B,
    SCENE_CHANNEL_FROM_DOWNLOADS = 0x7C,
    SCENE_TIME_TRIAL_LEADERBOARDS = 0x7D,
    SCENE_TOURNAMENT_LEADERBOARDS = 0x7E,
    SCENE_GHOST_RACE_WITH_DATA = 0x7F,
    SCENE_GHOST_RACE_WITHOUT_DATA = 0x80,
    SCENE_GHOST_RACE_NEXT_RACE = 0x81,
    SCENE_DOWNLOADED_GHOST_DATA = 0x82,
    SCENE_FRIENDS_LIST_1 = 0x83,
    SCENE_FRIENDS_LIST_2 = 0x84,
    SCENE_TOURNAMENT = 0x85,
    SCENE_TOURNAMENT_CHANGE_CHARA = 0x86,
    SCENE_TOURNAMENT_SUBMIT_RECORD = 0x87,
    SCENE_TOURNAMENT_WII_WHEEL_ONLY = 0x88,
    SCENE_TOURNAMENT_WII_WHEEL_ONLY_BOSSES = 0x89,
    SCENE_INVITE_FRIENDS_FROM_MSG_BOARD = 0x8A,
    SCENE_DOWNLOAD_LATEST_DATA = 0x8B,
    SCENE_OPTIONS = 0x8C,
    SCENE_INSTALL_CHANNEL = 0x8D,
    SCENE_CHOOSE_REGION = 0x8E,
    SCENE_JOIN_MESSAGE_SERVICE = 0x8F,
    SCENE_MSG_UNLOCK_PINK = 0x90,
    SCENE_MSG_UNLOCK_ORANGE = 0x91,
    SCENE_MSG_UNLOCK_BLUE = 0x92,
    SCENE_MSG_UNLOCK_YELLOW = 0x93,
    SCENE_BROKEN_MISSION_MODE_MENU = 0x94
};

class UIPageManager
{
public:
    void buildPage(s32 page);
    void showPageOnTop(s32 page);

    void setPage(s32 pageId, UIPage* page)
    {
        m_pages[pageId] = page;
    }

    UIPage* getPage(s32 pageId)
    {
        return m_pages[pageId];
    }

    int m_sceneId;
    u32 _4;
    UIPage* m_pages[210];
};

} // namespace UI
